spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatroom
    username: root
    password: myadmin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false